name: Backup Job CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[deploy]') || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
        with:
          repository: Honest-games/honest-secrets
          token: ${{secrets.CI_PAT}}
      - name: load-env
        uses: duskmoon314/action-load-env@v1.1.0
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          repository: ${{env.GITHUB_REPOSITORY}}
          token: ${{secrets.CI_PAT}}
      - name: Create folder
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{env.SSH_IP}}
          username: ${{env.SSH_USER}}
          password: ${{env.SSH_PASSWORD}}
          port: 22
          script: |
            mkdir -p /honest/honest-backup
      - name: Upload
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .
          remote: /honest/honest-backup
          host: ${{env.SSH_IP}}
          username: ${{env.SSH_USER}}
          password: ${{env.SSH_PASSWORD}}
          concurrency: 20
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{env.SSH_IP}}
          username: ${{env.SSH_USER}}
          password: ${{env.SSH_PASSWORD}}
          port: 22
          script: |
            export PG_CONN_STR=postgresql://${{env.PG_USER}}@${{env.PG_HOST}}:${{env.PG_PORT}}
            export PG_PASS=${{env.PG_PASS}}
            export TG_BOT_TOKEN=${{env.PG_BACKUP_TG_BOT_TOKEN}}
            export PG_BACKUP_TG_CHAT_ID=${{env.PG_BACKUP_TG_CHAT_ID}}
            
            cd /honest/honest-backup
            
            echo "conn str is $PG_CONN_STR"
            
            # TODO remove this
            docker login -u ${{env.DOCKER_USER}} -p ${{env.DOCKER_PAT}}
            
            docker compose pull
            docker compose down --remove-orphans
            docker compose up -d
